# Generated by Django 3.0.7 on 2020-09-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_abstract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
